name = "bk03/parameterized_simple"
version = "0.0.0"
compiler = "v1.1.9"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'bk03/parameterized_simple'"

[repository]
user = "bk03"
project = "parameterized_simple"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.2.0"
source = "github"

[config]
